BASE_DIRECTORY = '.server_files'
OUTPUT_DB = BASE_DIRECTORY + '/' +'comments_and_statuses'
OUTPUT_DIRECTORY = BASE_DIRECTORY + '/' + 'articles'
USERS_FILE = BASE_DIRECTORY + '/users.json'
DOIS_FILE = BASE_DIRECTORY + '/dois.csv'
FINDER_FILE = BASE_DIRECTORY + '/finder.txt'